<?php

/**
 * This is the model base class for the table "person".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Person".
 *
 * Columns in table "person" available as properties of the model,
 * followed by relations of table "person" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property Show[] $shows
 * @property Show[] $shows1
 */
abstract class BasePerson extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'person';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Person|People', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>400),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'shows' => array(self::MANY_MANY, 'Show', 'show_actor(person_id, show_id)'),
			'shows1' => array(self::MANY_MANY, 'Show', 'show_director(person_id, show_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'shows' => 'ShowActor',
			'shows1' => 'ShowDirector',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'shows' => null,
			'shows1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}