<?php

/**
 * This is the model base class for the table "channel".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Channel".
 *
 * Columns in table "channel" available as properties of the model,
 * followed by relations of table "channel" available as properties of the model.
 *
 * @property integer $id
 * @property string $slug
 * @property string $name
 * @property integer $active
 *
 * @property Schedule[] $schedules
 */
abstract class BaseChannel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'channel';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Channel|Channels', $n);
	}

	public static function representingColumn() {
		return 'slug';
	}

	public function rules() {
		return array(
			array('slug, name', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('slug, name', 'length', 'max'=>100),
			array('active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, slug, name, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'schedules' => array(self::HAS_MANY, 'Schedule', 'channel_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'slug' => Yii::t('app', 'Slug'),
			'name' => Yii::t('app', 'Name'),
			'active' => Yii::t('app', 'Active'),
			'schedules' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}