<?php

/**
 * This is the model base class for the table "schedule".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Schedule".
 *
 * Columns in table "schedule" available as properties of the model,
 * followed by relations of table "schedule" available as properties of the model.
 *
 * @property integer $id
 * @property string $start
 * @property integer $length
 * @property integer $channel_id
 * @property integer $show_id
 * @property string $day_date
 *
 * @property Channel $channel
 * @property Show $show
 */
abstract class BaseSchedule extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'schedule';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Schedule|Schedules', $n);
	}

	public static function representingColumn() {
		return 'start';
	}

	public function rules() {
		return array(
			array('start, length, channel_id, show_id, day_date', 'required'),
			array('length, channel_id, show_id', 'numerical', 'integerOnly'=>true),
			array('id, start, length, channel_id, show_id, day_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'channel' => array(self::BELONGS_TO, 'Channel', 'channel_id'),
			'show' => array(self::BELONGS_TO, 'Show', 'show_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'start' => Yii::t('app', 'Start'),
			'length' => Yii::t('app', 'Length'),
			'channel_id' => null,
			'show_id' => null,
			'day_date' => Yii::t('app', 'Day Date'),
			'channel' => null,
			'show' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('start', $this->start, true);
		$criteria->compare('length', $this->length);
		$criteria->compare('channel_id', $this->channel_id);
		$criteria->compare('show_id', $this->show_id);
		$criteria->compare('day_date', $this->day_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}