<?php

/**
 * This is the model base class for the table "show_actor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShowActor".
 *
 * Columns in table "show_actor" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $show_id
 * @property integer $person_id
 *
 */
abstract class BaseShowActor extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'show_actor';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ShowActor|ShowActors', $n);
	}

	public static function representingColumn() {
		return array(
			'show_id',
			'person_id',
		);
	}

	public function rules() {
		return array(
			array('show_id, person_id', 'required'),
			array('show_id, person_id', 'numerical', 'integerOnly'=>true),
			array('show_id, person_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'show_id' => null,
			'person_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('show_id', $this->show_id);
		$criteria->compare('person_id', $this->person_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}