<?php

/**
 * This is the model base class for the table "category_genre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CategoryGenre".
 *
 * Columns in table "category_genre" available as properties of the model,
 * followed by relations of table "category_genre" available as properties of the model.
 *
 * @property integer $id
 * @property integer $category_id
 * @property integer $genre_id
 *
 * @property Category $category
 * @property Genre $genre
 */
abstract class BaseCategoryGenre extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'category_genre';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CategoryGenre|CategoryGenres', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('category_id, genre_id', 'numerical', 'integerOnly'=>true),
			array('category_id, genre_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category_id, genre_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'Category', 'category_id'),
			'genre' => array(self::BELONGS_TO, 'Genre', 'genre_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => null,
			'genre_id' => null,
			'category' => null,
			'genre' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('genre_id', $this->genre_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}